"""Real numerical execution with explicitly prewritten modeling/review fixtures.
This is not evidence of live LLM mathematical-modeling performance.
"""
from __future__ import annotations
from pathlib import Path
import copy
from .common import *
from .controller import DEFAULT_CONFIG,Controller
from .intake import create_workspace
from .providers import FixtureProvider
from .sandbox import Executor

PLAN={
 'summary':'在合成的有限工件序列问题上同时最大化延迟折损收益并最小化总时长，构造有账本的近似前沿与独立小规模枚举评价。',
 'assumptions':['单机顺序加工；只能选择每个工件至多一次；允许非空子集。','收益随超过交期的时间线性折损，并截断为非负；这是合成任务假设。','所有评价确定；随机种子仅改变算法搜索，不构成不同任务。'],
 'questions':[{'id':'q1','question':'在给定计算预算下求取收益与时长的折中前沿。','metric':'normalized_hv','unit':'ratio','acceptance':'全部报告点的目标由独立实现重算，归一化超体积不大于精确有限域前沿。'},
              {'id':'q2','question':'给出预先定义折中规则下的可行推荐序列。','metric':'schedule_feasibility','unit':'boolean','acceptance':'推荐序列必须来自真实评估过的可行非空子集。'}],
 'tasks':[{'id':'validate','depends_on':[],'goal':'验证数据、量纲与可行编码','algorithm_skill':'statistics','outputs':['data checks']},
          {'id':'optimize','depends_on':['validate'],'goal':'等FE预算运行随机基准与MOSAIC','algorithm_skill':'mosaic-multiobjective','outputs':['paid ledger','candidate front']},
          {'id':'recommend','depends_on':['optimize'],'goal':'固定效用尺度选择代表序列并独立评价','algorithm_skill':'mosaic-multiobjective','outputs':['selected schedule','verified objectives']}],
 'variables':[{'symbol':'pi','meaning':'非空、不重复的工件序列','unit':'index'},{'symbol':'C_k','meaning':'第k个工件完成时刻','unit':'minutes'},
              {'symbol':'R','meaning':'总收益','unit':'reward_units'}],
 'equations':[r'C_k=C_{k-1}+s_{\pi_{k-1},\pi_k}+p_{\pi_k}',r'R=\sum_{k=1}^{|\pi|}\max\{0,v_{\pi_k}-w_{\pi_k}\max(C_k-d_{\pi_k},0)\}',r'\min\,(-R,C_{|\pi|})'],
 'constraints':['非空子集、无重复工件、合法随机键范围。','独立目标重算与付费账本成员关系一致。'],
 'baseline':'同一FE预算下的均匀随机键搜索与相同非支配后处理。',
 'ablations':[{'id':'no_infill','change':'只将相同SearchConfig的enabled置为False，其余引擎、参数和FE预算保持不变。'}],
 'sensitivity':[{'id':'population16','change':'种群由默认配置改为较小规模，保持FE预算和其余求解参数不变。'}],
 'limitations':['仅限当前合成实例；不代表完整国赛原题，也不证明跨问题优势。','多随机种子检验算法随机性，而非对独立数据集的泛化。'],
 'primary_metric':'normalized_hv','direction':'maximize','min_effect':0.,
 'evaluator_spec':'独立实现随机键解码和分段线性收益。重算所有付费目标、验证存档无假点，并枚举全部非空工件排列子集计算固定参考点的精确归一化超体积。',
 'resources':{'cpu_threads':1,'memory_mb':1024,'expected_seconds':20.,'row_sharding':False,'checkpointing':False,'fold_invariant_precompute':True}}

def code_bundle(strategy='fast_h0'):
    text=(ROOT/'examples/demo_source/main.py').read_text('utf-8').replace("FULL_STRATEGY = 'fast_h0'",f"FULL_STRATEGY = '{strategy}'")
    return {'files':[{'path':'main.py','content':text}],'notes':['PREWRITTEN_DEMO_FIXTURE; not generated by a live model'],
            'algorithm_usage':[{'skill':'mosaic-multiobjective','strategy':strategy,'reason':'admissible deterministic bi-objective ordered-subset task'}]}

def verifier_bundle():
    return {'files':[{'path':name,'content':(ROOT/'examples/demo_source'/name).read_text('utf-8')} for name in ('evaluate.py','test_solver.py')],
            'notes':['Independently implemented mathematical oracle; fixture authored before the experiment'], 'algorithm_usage':[]}

def responder(role,schema,packet):
    if schema=='review':return {'target_digest':packet['target_digest'],'verdict':'PASS','scope':'FIXTURE ONLY: exercise the review interface; this is NOT a real Claude/Codex review',
                               'findings':[],'evidence':['prewritten fixture; actual numerical verification is performed separately by the independent evaluator'],'unverified':[]}
    if schema=='supervisor':return {'objective':'验证完整工程链而不宣称大模型自主能力或SOTA','priorities':['冻结协议','运行真实代码','独立重算与披露边界'],'research_focus':['比较代理重拟合频率'],'stop_rules':['不改确认数据','不追逐确认集','最多配置中的候选数']}
    if schema=='proposal':return {'hypothesis':'更频繁重拟合代理可能改善局部排序。','mechanism':'仅改变已提供实验分支的重拟合间隔。',
                                 'expected_effect':'效果未知，允许负结果。','change_request':'Use explicitly experimental refit32 in the second candidate. Keep the evaluator, budgets and ablation mechanism fixed.',
                                 'falsification':'开发集没有改善则不进入确认主对比；确认结果不改善则保留基准。','stop':False}
    if role=='modeler':return copy.deepcopy(PLAN)
    if role=='coder':return code_bundle('refit32' if 'proposal' in packet else 'fast_h0')
    if role=='verifier_author':return verifier_bundle()
    if role=='writer':
        claims=packet['claims'];candidate=next((k for k in claims if k.startswith('mean_c')), 'mean_baseline')
        t=lambda key:'{{claim:'+key+'}}'
        abstract=('针对具有序列相关准备时间与交期折损收益的工件选择问题，建立收益与时长的双目标模型。采用付费评价账本记录全部搜索观测，'
           '使用独立实现重算目标，并在当前小规模有限域上枚举参考前沿。确认阶段基准归一化超体积均值为'+t('mean_baseline')+
           '，开发阶段选定方法的确认均值为'+t(candidate)+'，配对平均变化为'+t('mean_improvement')+'。结论仅限当前合成实例与预算，不能外推为跨题目优势。')
        return {'title':'面向可核验双目标序列优化的确定性实验与证据链','abstract':abstract,'keywords':['双目标优化','序列决策','独立评测','可复现实验'],
          'sections':[{'heading':'问题重述','text':'在给定工件集合中选取一个非空子集并确定加工顺序。收益随交期延迟折损，总加工时长含相邻工件之间的准备时间。目标是得到收益与时长的折中解，并按事先确定的效用尺度给出代表性建议。该实例为合成数据，不是任何官方完整赛题。','equations':[],'claim_ids':[]},
            {'heading':'假设、符号与数学模型','text':'工件不可重复，设备串行加工，所有时间与收益参数在当前实验中视为确定量。以工件序列作为决策变量，用连续随机键表示可行非空子集。下式分别给出完成时刻、总收益和双目标最小化形式。','equations':PLAN['equations'],'claim_ids':[]},
            {'heading':'求解、控制试验与独立验证','text':'随机搜索与定制优化器使用相同的函数评价预算、随机种子集合以及非支配后处理。独立评测器不导入优化器的目标函数，而是重新实现解码、收益计算与有限域枚举。搜索器不读取枚举参考前沿。消融只关闭代理预筛选开关，灵敏度试验只改变种群规模。开发试验用于选择候选，随后冻结候选才进行确认。','equations':[],'claim_ids':[]},
            {'heading':'结果与适用范围','text':'确认阶段的配对平均变化为'+t('mean_improvement')+'。以下表格中的数值直接来自经过独立评价的运行记录，而非语言模型补写。代表性运行的推荐序列收益为'+t('result_reward')+'，持续时间为'+t('result_duration')+'。代表性运行按确认得分的中位排序选择，不按最优单次结果挑选。','equations':[],'claim_ids':['mean_improvement','result_reward','result_duration']}],
          'limitations':['随机种子是当前实例上的重复实验单位，不能视为独立任务样本。','工程演示的模型规划、建议和审查来自测试夹具；这些回执不是实际多模型审查。','精确枚举只覆盖当前声明的有限决策域，不证明现实模型假设正确或其他题目的最优性。'],
          'figure_caption':'基于所提供矢量绘图代码构建的控制、执行、审查与论文证据链。','citation_ids':[]}
    raise ValueError((role,schema))

def run_demo(root:Path,*,candidates=2,fe_budget=192):
    if not root.exists() or not (root/'control.sqlite3').exists():
        src=root.parent/(root.name+'-inputs');src.mkdir(parents=True,exist_ok=True)
        n=6;setup=[[0. if i==j else float(1+(3*i+2*j)%5) for j in range(n)] for i in range(n+1)]
        spec={'id':'synthetic_job6','kind':'job','values':[15.,9.,12.,7.,11.,6.],
              'process':[4.,3.,5.,2.,4.,1.],'dues':[14.,9.,18.,6.,16.,5.],'penalty':[1.1,.8,1.2,1.,.9,.5],'setup':setup}
        write_json(src/'problem.json',spec);problem=root.parent/(root.name+'-problem.md')
        atomic_write(problem,'合成双目标工件选择与排序：在非空、不重复的工件序列上同时最大化延迟折损收益与最小化总时长。第一问求取Pareto前沿；第二问给出固定效用尺度下的可行代表方案。数据见problem.json。本实例是工程测试，不是官方国赛题。')
        config={**DEFAULT_CONFIG,'literature_enabled':False,'allow_research_algorithms':True,'max_candidates':candidates,'fe_budget':fe_budget}
        create_workspace(root,problem,src,config)
    provider=FixtureProvider(responder);executor=Executor('trusted-local')
    return Controller(root,fixture_provider=provider,executor=executor).run()
